#find libfsdetcore
include(FindPkgConfig)
pkg_search_module(FSDETCORE_LIB REQUIRED fsdetcore)

if(NOT FSDETCORE_LIB_FOUND)
  message(FATAL_ERROR "cannot find fsdetcore")
else(NOT FSDETCORE_LIB_FOUND)
  message(STATUS "fsdetcore include path:${FSDETCORE_LIB_INCLUDE_DIRS}")
  message(STATUS "fsdetcore lib path:${FSDETCORE_LIB_LIBRARY_DIRS}")
  message(STATUS "fsdetcore libs:${FSDETCORE_LIB_LIBRARIES}")
  message(STATUS "fsdetcore ld flags:${FSDETCORE_LIB_LDFLAGS}")
  message(STATUS "fsdetcore C flags:${FSDETCORE_LIB_CFLAGS}")
  # string (REPLACE ";" " " FSDETCORE_LIB_INCLUDE_DIRS  "${FSDETCORE_LIB_INCLUDE_DIRS}")
  # string (REPLACE ";" " " FSDETCORE_LIB_LIBRARY_DIRS  "${FSDETCORE_LIB_LIBRARY_DIRS}")
  # string (REPLACE ";" " " FSDETCORE_LIB_LIBRARIES  "${FSDETCORE_LIB_LIBRARIES}")
  # string (REPLACE ";" " " FSDETCORE_LIB_LDFLAGS  "${FSDETCORE_LIB_LDFLAGS}")
  # string (REPLACE ";" " " FSDETCORE_LIB_CFLAGS  "${FSDETCORE_LIB_CFLAGS}")
endif(NOT FSDETCORE_LIB_FOUND)
