TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = win32-x86
#ARCH = win32-x86-debug
#ARCH = windows-x64
#ARCH = windows-x64-debug
ARCH = linux-x86_64
#ARCH = linux-x86_64-debug
TARGETS = envPaths
include $(TOP)/configure/RULES.ioc
